"use client";
import {useEffect,useState} from "react";
const KEY="fih-chart-study-v1";
const defaults={date:"",timeframe:"5",direction:"Long",bos:"",fvg:"",fill:"",entry:"",stop:"",target:"",outcome:"Unreviewed",notes:"",fourHour:"Not checked"};
export default function ChartingLab(){
 const [form,setForm]=useState(defaults),[records,setRecords]=useState([]),[ready,setReady]=useState(false),[symbol,setSymbol]=useState("CME_MINI:NQ1!");
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||"[]");if(Array.isArray(x))setRecords(x.slice(0,100))}catch{}setReady(true)},[]);
 const set=(key,value)=>setForm(x=>({...x,[key]:value}));
 function save(){if(!form.date||!form.notes.trim())return;const next=[{...form,id:Date.now(),symbol},...records].slice(0,100);setRecords(next);try{localStorage.setItem(KEY,JSON.stringify(next))}catch{}setForm(defaults)}
 function remove(id){const next=records.filter(x=>x.id!==id);setRecords(next);try{localStorage.setItem(KEY,JSON.stringify(next))}catch{}}
 function exportCSV(){const columns=["date","symbol","timeframe","direction","fourHour","bos","fvg","fill","entry","stop","target","outcome","notes"];const csv=[columns.join(","),...records.map(r=>columns.map(k=>'"'+String(r[k]??"").replaceAll('"','""')+'"').join(","))].join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="futures-chart-studies.csv";a.click();URL.revokeObjectURL(a.href)}
 const widget="https://s.tradingview.com/widgetembed/?frameElementId=tv_chart_lab&symbol="+encodeURIComponent(symbol)+"&interval="+encodeURIComponent(form.timeframe)+"&hidesidetoolbar=0&symboledit=1&saveimage=1&toolbarbg=081425&studies=[]&theme=dark&style=1&timezone=America%2FNew_York&withdateranges=1&hideideas=1";
 return <><section className="panel"><div className="sectionTop"><div><small>02 / CHARTING LAB</small><h1>Historical NQ chart review</h1><p>Explore prior candles, spot break of structure (BOS), fair value gaps (FVG), fills and hypothetical entries. The embedded chart is controlled by TradingView and may have delayed data or historical limits.</p></div><span className="outline">TRAINING / MANUAL</span></div><div className="labtools"><label>Market <select value={symbol} onChange={e=>setSymbol(e.target.value)}><option value="CME_MINI:NQ1!">NQ continuous</option><option value="CME_MINI:MNQ1!">MNQ continuous</option></select></label><label>Timeframe <select value={form.timeframe} onChange={e=>set("timeframe",e.target.value)}><option value="240">4H</option><option value="60">1H</option><option value="15">15M</option><option value="5">5M</option></select></label><a href={"https://www.tradingview.com/chart/?symbol="+encodeURIComponent(symbol)} target="_blank" rel="noopener noreferrer">Open full TradingView chart ↗</a></div><div className="tvframe"><iframe key={symbol+"-"+form.timeframe} src={widget} title="TradingView Nasdaq futures historical chart" allowFullScreen loading="lazy" referrerPolicy="origin"/></div><p>Use the 4H to establish trend, 1H for structure, 15M for the setup and 5M for potential entry. Marking a historical opportunity does not establish that it was executable or profitable.</p></section>
 <section className="panel"><div className="sectionTop"><div><small>HISTORICAL SETUP LIBRARY</small><h1>Log BOS, FVG fills and missed entries</h1><p>Document actual chart examples to build a review library. Saved studies remain in this browser unless you export them; they do not train an AI model yet.</p></div><span className="outline">LOCAL STORAGE</span></div><div className="labform">
 <label>Session date <input type="date" value={form.date} onChange={e=>set("date",e.target.value)}/></label>
 <label>4H bias <select value={form.fourHour} onChange={e=>set("fourHour",e.target.value)}>{["Not checked","Bullish","Bearish","Neutral"].map(x=><option key={x}>{x}</option>)}</select></label>
 <label>Example direction <select value={form.direction} onChange={e=>set("direction",e.target.value)}><option>Long</option><option>Short</option></select></label>
 <label>BOS level <input type="number" step=".25" placeholder="Price or leave blank" value={form.bos} onChange={e=>set("bos",e.target.value)}/></label>
 <label>FVG zone (low–high) <input placeholder="e.g. 24000–24020" value={form.fvg} onChange={e=>set("fvg",e.target.value)}/></label>
 <label>FVG fill observation <select value={form.fill} onChange={e=>set("fill",e.target.value)}><option value="">Select</option><option>Fully filled</option><option>Partially filled</option><option>Unfilled</option></select></label>
 <label>Hypothetical entry <input type="number" step=".25" value={form.entry} onChange={e=>set("entry",e.target.value)}/></label>
 <label>Hypothetical stop <input type="number" step=".25" value={form.stop} onChange={e=>set("stop",e.target.value)}/></label>
 <label>Hypothetical target <input type="number" step=".25" value={form.target} onChange={e=>set("target",e.target.value)}/></label>
 <label>Review outcome <select value={form.outcome} onChange={e=>set("outcome",e.target.value)}>{["Unreviewed","Target reached after entry","Stop reached after entry","Ambiguous / neither","Invalid setup"].map(x=><option key={x}>{x}</option>)}</select></label>
 <label className="labwide">Chart observations and reasons <textarea rows="3" value={form.notes} placeholder="What broke structure? Where did price return to FVG? Why would the 5M entry qualify? What invalidates it?" onChange={e=>set("notes",e.target.value)}/></label></div><button className="action" disabled={!form.date||!form.notes.trim()} onClick={save}>Save historical example</button><button className="action secondary" disabled={!records.length} onClick={exportCSV}>Export studies CSV</button><div className="labrecords">{ready&&records.length===0?<p>No examples saved yet. Start with a past 5M chart and identify one clean BOS and FVG return.</p>:records.map(x=><div className="listItem" key={x.id}><div><strong>{x.date} · {x.symbol} · {x.direction} · {x.timeframe}m</strong><small>4H: {x.fourHour} · BOS: {x.bos||"—"} · FVG: {x.fvg||"—"} · {x.fill||"Fill not assessed"}</small><p>{x.notes}</p><small>Entry: {x.entry||"—"} · Stop: {x.stop||"—"} · Target: {x.target||"—"} · {x.outcome}</small></div><button className="labdelete" onClick={()=>remove(x.id)}>Delete</button></div>)}</div></section></>
}